In [1]:
import numpy as np
import pandas as pd

### 1. Create a vector (array) of 1XN dimension representing N-
dimensional feature vector of a sample. Write a program to

compute the mean and variance of the elements present in the
array.

In [14]:
def compute(n):
    #Mean
    mean=np.sum(n)/np.size(n)
    #Population Variance
    a=(n-mean)**2
    v1=np.sum(a)/np.size(n)
    return mean,v1
N=5
arr=np.random.rand(1,N)
mean,Population_variance=compute(arr)
print("Sample Vector: ",arr)
print("Mean: ",mean)
print("Population Variance: ",Population_variance)

Sample Vector:  [[0.04191182 0.83222769 0.67698859 0.56206456 0.69573622]]
Mean:  0.561785776237761
Population Variance:  0.07492444945931029


# 2. Create two vectors each of dimension 1XM each representing N-
dimensional feature vector of a sample. Write a program to

compute the Covariance between them.

In [19]:
def cov(n1,n2):
    mean1=np.sum(n1)/np.size(n1)
    mean2=np.sum(n2)/np.size(n2)
    a1=(n1-mean1)
    a2=(n2-mean2)
    b=a1*a2
    covariance=np.sum(b)/(np.size(n1)-1)
    return covariance
M=5
arr1=np.random.rand(1,M)
arr2=np.random.rand(1,M)
c=cov(arr1,arr2)
print("Vector 1: ",arr1)
print("Vector 2: ",arr2)
print("Covariance: ",c)

Vector 1:  [[0.69554501 0.81573708 0.59869185 0.1119828  0.53827259]]
Vector 2:  [[0.54358184 0.07379107 0.69592739 0.738065   0.28053061]]
Covariance:  -0.04968379264083387


# Create two vectors each of dimension 1XN. Write a program to
compute the Correlation between them.

Comment what the Correlation represents.

In [21]:
def Cor(n1,n2):
    covariance=cov(n1,n2)
    m1,v1=compute(n1)
    m2,v2=compute(n2)
    k=np.sqrt(v1)*np.sqrt(v2)
    correlation=covariance/k
    return correlation
N=5
arr1=np.random.rand(1,N)
arr2=np.random.rand(1,N)
corr=Cor(arr1,arr2)
print("Vector 1: ",arr1)
print("Vector 2: ",arr2)
print("Correlation: ",corr)

Vector 1:  [[0.89515331 0.40952396 0.86014463 0.08637972 0.91126682]]
Vector 2:  [[0.18139529 0.13857302 0.94724397 0.4944088  0.88767736]]
Correlation:  0.46670724356172005


# 4. Create a Matrix of MXN dimension representing the M-dimensional
feature vector for N number of samples i. e (i,j)th entry of the matrix
represents the ith feature of jth sample. Write a program to compute
the covariance matrix and correlation matrix. Comment on
takeaways from these matrixes.

In [22]:
import numpy as np

def cov_matrix(matrix):
    cov_m= np.cov(matrix)

    return cov_m

def corr_matrix(matrix):
    corr_m = np.corrcoef(matrix)

    return corr_m

M = 3 
N = 5  
feature_matrix = np.random.rand(M, N)
covariance_matrix = cov_matrix(feature_matrix)
correlation_matrix = corr_matrix(feature_matrix)

print("Feature Matrix:")
print(feature_matrix)
print("\nCovariance Matrix:")
print(covariance_matrix)
print("\nCorrelation Matrix:")
print(correlation_matrix)


Feature Matrix:
[[0.91381178 0.77816384 0.32483007 0.560147   0.50479307]
 [0.88597105 0.780656   0.3493493  0.32212784 0.77615114]
 [0.90513471 0.72400043 0.99511125 0.37654673 0.76194217]]

Covariance Matrix:
[[ 0.05381371  0.04583356 -0.00246457]
 [ 0.04583356  0.07071828  0.02095366]
 [-0.00246457  0.02095366  0.05609995]]

Correlation Matrix:
[[ 1.          0.74297004 -0.04485529]
 [ 0.74297004  1.          0.33266932]
 [-0.04485529  0.33266932  1.        ]]
